# Generated by Django 4.2.1 on 2023-06-07 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Курс')),
                ('description', models.CharField(max_length=370, null=True, verbose_name='Описание')),
                ('duration', models.DecimalField(decimal_places=0, max_digits=6, max_length=10, verbose_name='Длительность')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['title'],
            },
        ),
    ]
